name: Release | 发布

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: # click the button on Github repo!

permissions:
  contents: write

jobs:
  release:
    name: Build and Release
    if: github.repository == 'misix-themes/static-theme-misilog'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Nodejs | 设置 NodeJS 环境
        uses: actions/setup-node@v2
        with:
          node-version: 16.17.0

      - name: Install dependencies and build | 安装依赖并构建
        run: npm install && npm run build

      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          body: 'release: ${{  github.ref_name }}'
          artifacts: ''
          token: ${{ secrets.GITHUB_TOKEN  }}
